
all:
	@(cd QtDeclarative; $(MAKE))
	@(cd QtCore; $(MAKE))
	@(cd QtGui; $(MAKE))
#	@(cd QtDesigner; $(MAKE))

install:
	@(cd QtDeclarative; $(MAKE) install)
	@(cd QtCore; $(MAKE) install)
	@(cd QtGui; $(MAKE) install)
#	@(cd QtDesigner; $(MAKE) install)

clean:
	@(cd QtDeclarative; $(MAKE) clean)
	@(cd QtCore; $(MAKE) clean)
	@(cd QtGui; $(MAKE) clean)
#	@(cd QtDesigner; $(MAKE) clean)
