/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.11.2 on Thu Jul 12 20:03:16 2012
 *
 * Copyright (c) 2010 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtGui.h"

#line 1929 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtGui/qstyleoption.sip"
#include <qstyleoption.h>
#line 39 "sipQtGuiQStyleOptionFrameV3.cpp"

#line 36 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtGui/qframe.sip"
#include <qframe.h>
#line 43 "sipQtGuiQStyleOptionFrameV3.cpp"
#line 375 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtGui/qstyleoption.sip"
#include <qstyleoption.h>
#line 46 "sipQtGuiQStyleOptionFrameV3.cpp"
#line 40 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 49 "sipQtGuiQStyleOptionFrameV3.cpp"


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QStyleOptionFrameV3(void *, const sipTypeDef *);}
static void *cast_QStyleOptionFrameV3(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QStyleOptionFrameV3)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QStyleOptionFrameV2)->ctd_cast((QStyleOptionFrameV2 *)(QStyleOptionFrameV3 *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QStyleOptionFrameV3(void *, int);}
static void release_QStyleOptionFrameV3(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QStyleOptionFrameV3 *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_QStyleOptionFrameV3(void *, SIP_SSIZE_T, const void *);}
static void assign_QStyleOptionFrameV3(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QStyleOptionFrameV3 *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QStyleOptionFrameV3 *>(sipSrc);
}


extern "C" {static void *array_QStyleOptionFrameV3(SIP_SSIZE_T);}
static void *array_QStyleOptionFrameV3(SIP_SSIZE_T sipNrElem)
{
    return new QStyleOptionFrameV3[sipNrElem];
}


extern "C" {static void *copy_QStyleOptionFrameV3(const void *, SIP_SSIZE_T);}
static void *copy_QStyleOptionFrameV3(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QStyleOptionFrameV3(reinterpret_cast<const QStyleOptionFrameV3 *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QStyleOptionFrameV3(sipSimpleWrapper *);}
static void dealloc_QStyleOptionFrameV3(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QStyleOptionFrameV3(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_QStyleOptionFrameV3(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QStyleOptionFrameV3(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QStyleOptionFrameV3 *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QStyleOptionFrameV3();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const QStyleOptionFrameV3 * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QStyleOptionFrameV3, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QStyleOptionFrameV3(*a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const QStyleOptionFrame * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QStyleOptionFrame, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QStyleOptionFrameV3(*a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QStyleOptionFrameV3[] = {{515, 255, 1}};

static sipEnumMemberDef enummembers_QStyleOptionFrameV3[] = {
    {sipName_Version, QStyleOptionFrameV3::Version, 520},
};


extern "C" {static PyObject *varget_QStyleOptionFrameV3_frameShape(void *, PyObject *);}
static PyObject *varget_QStyleOptionFrameV3_frameShape(void *sipSelf, PyObject *)
{
    QFrame::Shape sipVal;
    QStyleOptionFrameV3 *sipCpp = reinterpret_cast<QStyleOptionFrameV3 *>(sipSelf);

    sipVal = sipCpp->frameShape;

    return sipConvertFromEnum(sipVal, sipType_QFrame_Shape);
}


extern "C" {static int varset_QStyleOptionFrameV3_frameShape(void *, PyObject *, PyObject *);}
static int varset_QStyleOptionFrameV3_frameShape(void *sipSelf, PyObject *sipPy, PyObject *)
{
    QFrame::Shape sipVal;
    QStyleOptionFrameV3 *sipCpp = reinterpret_cast<QStyleOptionFrameV3 *>(sipSelf);

    sipVal = (QFrame::Shape)SIPLong_AsLong(sipPy);

    if (PyErr_Occurred() != NULL)
        return -1;

    sipCpp->frameShape = sipVal;

    return 0;
}


extern "C" {static PyObject *varget_QStyleOptionFrameV3_unused(void *, PyObject *);}
static PyObject *varget_QStyleOptionFrameV3_unused(void *sipSelf, PyObject *)
{
    uint sipVal;
    QStyleOptionFrameV3 *sipCpp = reinterpret_cast<QStyleOptionFrameV3 *>(sipSelf);

    sipVal = sipCpp->unused;

    return PyLong_FromUnsignedLong(sipVal);
}


extern "C" {static int varset_QStyleOptionFrameV3_unused(void *, PyObject *, PyObject *);}
static int varset_QStyleOptionFrameV3_unused(void *sipSelf, PyObject *sipPy, PyObject *)
{
    uint sipVal;
    QStyleOptionFrameV3 *sipCpp = reinterpret_cast<QStyleOptionFrameV3 *>(sipSelf);

    sipVal = (uint)sipLong_AsUnsignedLong(sipPy);

    if (PyErr_Occurred() != NULL)
        return -1;

    sipCpp->unused = sipVal;

    return 0;
}

sipVariableDef variables_QStyleOptionFrameV3[] = {
    {sipName_frameShape, varget_QStyleOptionFrameV3_frameShape, varset_QStyleOptionFrameV3_frameShape, 0},
    {sipName_unused, varget_QStyleOptionFrameV3_unused, varset_QStyleOptionFrameV3_unused, 0},
};


pyqt4ClassTypeDef sipTypeDef_QtGui_QStyleOptionFrameV3 = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QStyleOptionFrameV3,
        {0}
    },
    {
        sipNameNr_QStyleOptionFrameV3,
        {0, 0, 1},
        0, 0,
        1, enummembers_QStyleOptionFrameV3,
        2, variables_QStyleOptionFrameV3,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QStyleOptionFrameV3,
    0,
    init_QStyleOptionFrameV3,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QStyleOptionFrameV3,
    assign_QStyleOptionFrameV3,
    array_QStyleOptionFrameV3,
    copy_QStyleOptionFrameV3,
    release_QStyleOptionFrameV3,
    cast_QStyleOptionFrameV3,
    0,
    0,
    0
},
    0,
    0,
    0
};
