/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.11.2 on Thu Jul 12 20:03:20 2012
 *
 * Copyright (c) 2010 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtGui.h"

#line 232 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtGui/qbrush.sip"
#include <qbrush.h>
#line 39 "sipQtGuiQRadialGradient.cpp"

#line 92 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 43 "sipQtGuiQRadialGradient.cpp"
#line 152 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtGui/qbrush.sip"
#include <qbrush.h>
#line 46 "sipQtGuiQRadialGradient.cpp"
#line 208 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtCore/qvector.sip"
#include <qvector.h>
#include <qpair.h>
#line 50 "sipQtGuiQRadialGradient.cpp"
#line 40 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtGui/qcolor.sip"
#include <qcolor.h>
#line 53 "sipQtGuiQRadialGradient.cpp"


extern "C" {static PyObject *meth_QRadialGradient_center(PyObject *, PyObject *);}
static PyObject *meth_QRadialGradient_center(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QRadialGradient *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QRadialGradient, &sipCpp))
        {
            QPointF *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QPointF(sipCpp->center());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QPointF,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QRadialGradient, sipName_center, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QRadialGradient_focalPoint(PyObject *, PyObject *);}
static PyObject *meth_QRadialGradient_focalPoint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QRadialGradient *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QRadialGradient, &sipCpp))
        {
            QPointF *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QPointF(sipCpp->focalPoint());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QPointF,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QRadialGradient, sipName_focalPoint, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QRadialGradient_radius(PyObject *, PyObject *);}
static PyObject *meth_QRadialGradient_radius(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QRadialGradient *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QRadialGradient, &sipCpp))
        {
            qreal sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->radius();
            Py_END_ALLOW_THREADS

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QRadialGradient, sipName_radius, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QRadialGradient_setCenter(PyObject *, PyObject *);}
static PyObject *meth_QRadialGradient_setCenter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QPointF * a0;
        QRadialGradient *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QRadialGradient, &sipCpp, sipType_QPointF, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setCenter(*a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        qreal a0;
        qreal a1;
        QRadialGradient *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bdd", &sipSelf, sipType_QRadialGradient, &sipCpp, &a0, &a1))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setCenter(a0,a1);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QRadialGradient, sipName_setCenter, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QRadialGradient_setFocalPoint(PyObject *, PyObject *);}
static PyObject *meth_QRadialGradient_setFocalPoint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QPointF * a0;
        QRadialGradient *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QRadialGradient, &sipCpp, sipType_QPointF, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setFocalPoint(*a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        qreal a0;
        qreal a1;
        QRadialGradient *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bdd", &sipSelf, sipType_QRadialGradient, &sipCpp, &a0, &a1))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setFocalPoint(a0,a1);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QRadialGradient, sipName_setFocalPoint, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QRadialGradient_setRadius(PyObject *, PyObject *);}
static PyObject *meth_QRadialGradient_setRadius(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        qreal a0;
        QRadialGradient *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bd", &sipSelf, sipType_QRadialGradient, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setRadius(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QRadialGradient, sipName_setRadius, NULL);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QRadialGradient(void *, const sipTypeDef *);}
static void *cast_QRadialGradient(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QRadialGradient)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QGradient)->ctd_cast((QGradient *)(QRadialGradient *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QRadialGradient(void *, int);}
static void release_QRadialGradient(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QRadialGradient *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_QRadialGradient(void *, SIP_SSIZE_T, const void *);}
static void assign_QRadialGradient(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QRadialGradient *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QRadialGradient *>(sipSrc);
}


extern "C" {static void *array_QRadialGradient(SIP_SSIZE_T);}
static void *array_QRadialGradient(SIP_SSIZE_T sipNrElem)
{
    return new QRadialGradient[sipNrElem];
}


extern "C" {static void *copy_QRadialGradient(const void *, SIP_SSIZE_T);}
static void *copy_QRadialGradient(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QRadialGradient(reinterpret_cast<const QRadialGradient *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QRadialGradient(sipSimpleWrapper *);}
static void dealloc_QRadialGradient(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QRadialGradient(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_QRadialGradient(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QRadialGradient(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QRadialGradient *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QRadialGradient();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const QPointF * a0;
        qreal a1;
        const QPointF * a2;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9dJ9", sipType_QPointF, &a0, &a1, sipType_QPointF, &a2))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QRadialGradient(*a0,a1,*a2);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const QPointF * a0;
        qreal a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9d", sipType_QPointF, &a0, &a1))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QRadialGradient(*a0,a1);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        qreal a0;
        qreal a1;
        qreal a2;
        qreal a3;
        qreal a4;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "ddddd", &a0, &a1, &a2, &a3, &a4))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QRadialGradient(a0,a1,a2,a3,a4);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        qreal a0;
        qreal a1;
        qreal a2;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "ddd", &a0, &a1, &a2))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QRadialGradient(a0,a1,a2);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const QRadialGradient * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QRadialGradient, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QRadialGradient(*a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QRadialGradient[] = {{150, 255, 1}};


static PyMethodDef methods_QRadialGradient[] = {
    {SIP_MLNAME_CAST(sipName_center), meth_QRadialGradient_center, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_focalPoint), meth_QRadialGradient_focalPoint, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_radius), meth_QRadialGradient_radius, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setCenter), meth_QRadialGradient_setCenter, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setFocalPoint), meth_QRadialGradient_setFocalPoint, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_setRadius), meth_QRadialGradient_setRadius, METH_VARARGS, NULL}
};


pyqt4ClassTypeDef sipTypeDef_QtGui_QRadialGradient = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QRadialGradient,
        {0}
    },
    {
        sipNameNr_QRadialGradient,
        {0, 0, 1},
        6, methods_QRadialGradient,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QRadialGradient,
    0,
    init_QRadialGradient,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QRadialGradient,
    assign_QRadialGradient,
    array_QRadialGradient,
    copy_QRadialGradient,
    release_QRadialGradient,
    cast_QRadialGradient,
    0,
    0,
    0
},
    0,
    0,
    0
};
