/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.11.2 on Thu Jul 12 20:03:17 2012
 *
 * Copyright (c) 2010 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtGui.h"

#line 66 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 39 "sipQtGuiQPaintEngineDirtyFlags.cpp"

#line 66 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 43 "sipQtGuiQPaintEngineDirtyFlags.cpp"


extern "C" {static int slot_QPaintEngine_DirtyFlags___bool__(PyObject *);}
static int slot_QPaintEngine_DirtyFlags___bool__(PyObject *sipSelf)
{
    QPaintEngine::DirtyFlags *sipCpp = reinterpret_cast<QPaintEngine::DirtyFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QPaintEngine_DirtyFlags));

    if (!sipCpp)
        return -1;


    {
        {
            int sipRes = 0;

#line 336 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator int() != 0);
#line 61 "sipQtGuiQPaintEngineDirtyFlags.cpp"

            return sipRes;
        }
    }
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___ne__(PyObject *,PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___ne__(PyObject *sipSelf,PyObject *sipArg)
{
    QPaintEngine::DirtyFlags *sipCpp = reinterpret_cast<QPaintEngine::DirtyFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QPaintEngine_DirtyFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QPaintEngine::DirtyFlags * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QPaintEngine_DirtyFlags, &a0, &a0State))
        {
            bool sipRes = 0;

#line 331 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator int() != a0->operator int());
#line 89 "sipQtGuiQPaintEngineDirtyFlags.cpp"
            sipReleaseType(const_cast<QPaintEngine::DirtyFlags *>(a0),sipType_QPaintEngine_DirtyFlags,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,ne_slot,sipType_QPaintEngine_DirtyFlags,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___eq__(PyObject *,PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___eq__(PyObject *sipSelf,PyObject *sipArg)
{
    QPaintEngine::DirtyFlags *sipCpp = reinterpret_cast<QPaintEngine::DirtyFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QPaintEngine_DirtyFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QPaintEngine::DirtyFlags * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QPaintEngine_DirtyFlags, &a0, &a0State))
        {
            bool sipRes = 0;

#line 326 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator int() == a0->operator int());
#line 125 "sipQtGuiQPaintEngineDirtyFlags.cpp"
            sipReleaseType(const_cast<QPaintEngine::DirtyFlags *>(a0),sipType_QPaintEngine_DirtyFlags,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,eq_slot,sipType_QPaintEngine_DirtyFlags,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___invert__(PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___invert__(PyObject *sipSelf)
{
    QPaintEngine::DirtyFlags *sipCpp = reinterpret_cast<QPaintEngine::DirtyFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QPaintEngine_DirtyFlags));

    if (!sipCpp)
        return 0;


    {
        {
            QPaintEngine::DirtyFlags *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QPaintEngine::DirtyFlags(~(*sipCpp));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QPaintEngine_DirtyFlags,NULL);
        }
    }
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___and__(PyObject *,PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___and__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
        QPaintEngine::DirtyFlags * a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QPaintEngine_DirtyFlags, &a0, &a0State, &a1))
        {
            QPaintEngine::DirtyFlags *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QPaintEngine::DirtyFlags((*a0 & a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QPaintEngine_DirtyFlags,a0State);

            return sipConvertFromNewType(sipRes,sipType_QPaintEngine_DirtyFlags,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,and_slot,NULL,sipArg0,sipArg1);
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___xor__(PyObject *,PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___xor__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
        QPaintEngine::DirtyFlags * a0;
        int a0State = 0;
        QPaintEngine::DirtyFlags * a1;
        int a1State = 0;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1J1", sipType_QPaintEngine_DirtyFlags, &a0, &a0State, sipType_QPaintEngine_DirtyFlags, &a1, &a1State))
        {
            QPaintEngine::DirtyFlags *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QPaintEngine::DirtyFlags((*a0 ^ *a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QPaintEngine_DirtyFlags,a0State);
            sipReleaseType(a1,sipType_QPaintEngine_DirtyFlags,a1State);

            return sipConvertFromNewType(sipRes,sipType_QPaintEngine_DirtyFlags,NULL);
        }
    }

    {
        QPaintEngine::DirtyFlags * a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QPaintEngine_DirtyFlags, &a0, &a0State, &a1))
        {
            QPaintEngine::DirtyFlags *sipRes = 0;

#line 320 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtCore/qglobal.sip"
        sipRes = new QPaintEngine::DirtyFlags(*a0 ^ a1);
#line 232 "sipQtGuiQPaintEngineDirtyFlags.cpp"
            sipReleaseType(a0,sipType_QPaintEngine_DirtyFlags,a0State);

            return sipConvertFromNewType(sipRes,sipType_QPaintEngine_DirtyFlags,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,xor_slot,NULL,sipArg0,sipArg1);
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___or__(PyObject *,PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___or__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
        QPaintEngine::DirtyFlags * a0;
        int a0State = 0;
        QPaintEngine::DirtyFlags * a1;
        int a1State = 0;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1J1", sipType_QPaintEngine_DirtyFlags, &a0, &a0State, sipType_QPaintEngine_DirtyFlags, &a1, &a1State))
        {
            QPaintEngine::DirtyFlags *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QPaintEngine::DirtyFlags((*a0 | *a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QPaintEngine_DirtyFlags,a0State);
            sipReleaseType(a1,sipType_QPaintEngine_DirtyFlags,a1State);

            return sipConvertFromNewType(sipRes,sipType_QPaintEngine_DirtyFlags,NULL);
        }
    }

    {
        QPaintEngine::DirtyFlags * a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QPaintEngine_DirtyFlags, &a0, &a0State, &a1))
        {
            QPaintEngine::DirtyFlags *sipRes = 0;

#line 315 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtCore/qglobal.sip"
        sipRes = new QPaintEngine::DirtyFlags(*a0 | a1);
#line 284 "sipQtGuiQPaintEngineDirtyFlags.cpp"
            sipReleaseType(a0,sipType_QPaintEngine_DirtyFlags,a0State);

            return sipConvertFromNewType(sipRes,sipType_QPaintEngine_DirtyFlags,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,or_slot,NULL,sipArg0,sipArg1);
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___int__(PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___int__(PyObject *sipSelf)
{
    QPaintEngine::DirtyFlags *sipCpp = reinterpret_cast<QPaintEngine::DirtyFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QPaintEngine_DirtyFlags));

    if (!sipCpp)
        return 0;


    {
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = *sipCpp;
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___ixor__(PyObject *,PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___ixor__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QPaintEngine_DirtyFlags)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

    QPaintEngine::DirtyFlags *sipCpp = reinterpret_cast<QPaintEngine::DirtyFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QPaintEngine_DirtyFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        QPaintEngine::DirtyFlags * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QPaintEngine_DirtyFlags, &a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->QPaintEngine::DirtyFlags::operator^=(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QPaintEngine_DirtyFlags,a0State);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___ior__(PyObject *,PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___ior__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QPaintEngine_DirtyFlags)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

    QPaintEngine::DirtyFlags *sipCpp = reinterpret_cast<QPaintEngine::DirtyFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QPaintEngine_DirtyFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        QPaintEngine::DirtyFlags * a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QPaintEngine_DirtyFlags, &a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->QPaintEngine::DirtyFlags::operator|=(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QPaintEngine_DirtyFlags,a0State);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QPaintEngine_DirtyFlags___iand__(PyObject *,PyObject *);}
static PyObject *slot_QPaintEngine_DirtyFlags___iand__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QPaintEngine_DirtyFlags)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

    QPaintEngine::DirtyFlags *sipCpp = reinterpret_cast<QPaintEngine::DirtyFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QPaintEngine_DirtyFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->QPaintEngine::DirtyFlags::operator&=(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QPaintEngine_DirtyFlags(void *, const sipTypeDef *);}
static void *cast_QPaintEngine_DirtyFlags(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QPaintEngine_DirtyFlags)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QPaintEngine_DirtyFlags(void *, int);}
static void release_QPaintEngine_DirtyFlags(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QPaintEngine::DirtyFlags *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_QPaintEngine_DirtyFlags(void *, SIP_SSIZE_T, const void *);}
static void assign_QPaintEngine_DirtyFlags(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QPaintEngine::DirtyFlags *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QPaintEngine::DirtyFlags *>(sipSrc);
}


extern "C" {static void *array_QPaintEngine_DirtyFlags(SIP_SSIZE_T);}
static void *array_QPaintEngine_DirtyFlags(SIP_SSIZE_T sipNrElem)
{
    return new QPaintEngine::DirtyFlags[sipNrElem];
}


extern "C" {static void *copy_QPaintEngine_DirtyFlags(const void *, SIP_SSIZE_T);}
static void *copy_QPaintEngine_DirtyFlags(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QPaintEngine::DirtyFlags(reinterpret_cast<const QPaintEngine::DirtyFlags *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QPaintEngine_DirtyFlags(sipSimpleWrapper *);}
static void dealloc_QPaintEngine_DirtyFlags(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QPaintEngine_DirtyFlags(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_QPaintEngine_DirtyFlags(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QPaintEngine_DirtyFlags(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QPaintEngine::DirtyFlags *sipCpp = 0;

    {
        const QPaintEngine::DirtyFlags * a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1", sipType_QPaintEngine_DirtyFlags, &a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QPaintEngine::DirtyFlags(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QPaintEngine::DirtyFlags *>(a0),sipType_QPaintEngine_DirtyFlags,a0State);

            return sipCpp;
        }
    }

    {
        int a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "i", &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QPaintEngine::DirtyFlags(a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QPaintEngine::DirtyFlags();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


extern "C" {static int convertTo_QPaintEngine_DirtyFlags(PyObject *, void **, int *, PyObject *);}
static int convertTo_QPaintEngine_DirtyFlags(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QPaintEngine::DirtyFlags **sipCppPtr = reinterpret_cast<QPaintEngine::DirtyFlags **>(sipCppPtrV);

#line 341 "/home/tsheasha/GUC/Bachelors/android-python27/python-build/PyQt-x11-gpl-4.8/sip/QtCore/qglobal.sip"
// Allow an instance of the base enum whenever a QPaintEngine::DirtyFlags is expected.

if (sipIsErr == NULL)
    return (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QPaintEngine_DirtyFlag)) ||
            sipCanConvertToType(sipPy, sipType_QPaintEngine_DirtyFlags, SIP_NO_CONVERTORS));

if (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QPaintEngine_DirtyFlag)))
{
    *sipCppPtr = new QPaintEngine::DirtyFlags(SIPLong_AsLong(sipPy));

    return sipGetState(sipTransferObj);
}

*sipCppPtr = reinterpret_cast<QPaintEngine::DirtyFlags *>(sipConvertToType(sipPy, sipType_QPaintEngine_DirtyFlags, sipTransferObj, SIP_NO_CONVERTORS, 0, sipIsErr));

return 0;
#line 577 "sipQtGuiQPaintEngineDirtyFlags.cpp"
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QPaintEngine_DirtyFlags[] = {
    {(void *)slot_QPaintEngine_DirtyFlags___bool__, bool_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___ne__, ne_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___eq__, eq_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___invert__, invert_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___and__, and_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___xor__, xor_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___or__, or_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___int__, int_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___ixor__, ixor_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___ior__, ior_slot},
    {(void *)slot_QPaintEngine_DirtyFlags___iand__, iand_slot},
    {0, (sipPySlotType)0}
};


pyqt4ClassTypeDef sipTypeDef_QtGui_QPaintEngine_DirtyFlags = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QPaintEngine__DirtyFlags,
        {0}
    },
    {
        sipNameNr_DirtyFlags,
        {358, 255, 0},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    sipNameNr_sip_simplewrapper,
    0,
    slots_QPaintEngine_DirtyFlags,
    init_QPaintEngine_DirtyFlags,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QPaintEngine_DirtyFlags,
    assign_QPaintEngine_DirtyFlags,
    array_QPaintEngine_DirtyFlags,
    copy_QPaintEngine_DirtyFlags,
    release_QPaintEngine_DirtyFlags,
    cast_QPaintEngine_DirtyFlags,
    convertTo_QPaintEngine_DirtyFlags,
    0,
    0
},
    0,
    1,
    0
};
