#!/usr/bin/env python

import sys
import subprocess

libs = [ ]
objects = [ ]
output = None


i = 1
while i < len(sys.argv):
    opt = sys.argv[i]
    i += 1

    if opt == "-o":
        output = sys.argv[i]
        i += 1
        continue

    if opt.startswith("-l") or opt.startswith("-L"):
        libs.append(opt)
        continue

    if opt == "-r":
        continue

    if opt.startswith("-I"):
        continue

    if opt.startswith("-m"):
        continue

    if opt.startswith("-f"):
        continue

    if opt.startswith("-O"):
        continue

    if opt == "--sysroot":
        i += 1
        continue

    if opt.startswith("-D"):
        continue
    
    if opt.startswith("-"):
        print sys.argv
        print "Unknown option: ", opt
        sys.exit(1)

    objects.append(opt)


f = file(output, "w")
f.close()

f = file(output + ".libs", "w")
f.write(" ".join(libs))
f.close()

subprocess.call([ "arm-linux-androideabi-ld", "-r", "-o", output + ".o" ] + objects)


        
    
        
